# Generated by Django 2.2.9 on 2020-03-02 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dexNum', models.IntegerField(default=1)),
                ('frontImg', models.CharField(default='SOME STRING', max_length=300)),
                ('backImg', models.CharField(default='SOME STRING', max_length=300)),
                ('hp', models.IntegerField(default=1)),
                ('attack', models.IntegerField(default=1)),
                ('defence', models.IntegerField(default=1)),
                ('spAt', models.IntegerField(default=1)),
                ('spDf', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('type1', models.CharField(default='normal', max_length=50)),
                ('type2', models.CharField(default='none', max_length=50)),
                ('shape', models.CharField(default='SOME STRING', max_length=50)),
                ('height', models.IntegerField(default=1)),
                ('eggGroup', models.CharField(default='SOME STRING', max_length=50)),
                ('isBaby', models.BooleanField(null=True)),
                ('generation', models.CharField(default='SOME STRING', max_length=50)),
                ('description', models.TextField(default='SOME STRING')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
